{{- if .Values.balancer.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: juice-shops
  labels:
    {{- include "multi-juicer.juice-shop.labels" . | nindent 4 }}
    {{- with .Values.balancer.metrics.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.balancer.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetLabels:
    - team
  selector:
    matchLabels:
      app.kubernetes.io/name: 'juice-shop'
      app.kubernetes.io/part-of: multi-juicer
  endpoints:
    - targetPort: 3000
{{- end }}